package ru.qmurzik.qmodstools.feature;

import ru.qmurzik.qmodstools.QModsTools;
import ru.qmurzik.qmodstools.util.ColorUtil;
import ru.qmurzik.qmodstools.util.DrawUtil;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Properties;

/** UI, focus mode, result screen and hit-sound presets for 1.7.0. */
public final class QModsV17 {
    public static final String[] CATEGORIES={"БОЙ","BEDWARS","HUD","ЧАТ","ВНЕШНОСТЬ","ПРОИЗВОДИТЕЛЬНОСТЬ","ЗВУКИ"};
    public static final String[] THEMES={"Violet","Ice","Sakura","Crimson"};
    public static final String[] SOUND_NAMES={"Classic","Pop","Click","Crystal","Arcade","Без звука"};
    public static boolean focusMode=true;public static int focusSeconds=3,soundPreset=0,uiTheme=0;
    private static Object mc;private static long combatUntil,lastCustomHit,resultUntil;private static boolean focusApplied,loaded;
    private static boolean oldBw,oldPing,oldCps,oldCoords;private static File settingsFile;
    private static Result result;
    private QModsV17(){}

    public static void tick(Object minecraft){mc=minecraft;load();boolean active=isConcentrating();if(active&&!focusApplied){focusApplied=true;oldBw=QModsTools.config.bedWarsHud;oldPing=QModsTools.config.pingHud;oldCps=QModsTools.config.cpsHud;oldCoords=QModsTools.config.coordsHud;QModsTools.config.bedWarsHud=false;QModsTools.config.pingHud=false;QModsTools.config.cpsHud=false;QModsTools.config.coordsHud=false;}else if(!active&&focusApplied){focusApplied=false;QModsTools.config.bedWarsHud=oldBw;QModsTools.config.pingHud=oldPing;QModsTools.config.cpsHud=oldCps;QModsTools.config.coordsHud=oldCoords;}}
    public static boolean isConcentrating(){return focusMode&&System.currentTimeMillis()<combatUntil;}
    public static void onHurt(Object event,Object minecraft){mc=minecraft;Object target=field(event,"entityLiving"),source=field(event,"source"),attacker=call(source,"func_76346_g","getEntity"),player=field(mc,"field_71439_g","thePlayer");if(target==player||attacker==player)combatUntil=System.currentTimeMillis()+focusSeconds*1000L;if(attacker==player&&target!=player){lastCustomHit=System.currentTimeMillis();playPreset();}}
    public static void onSound(Object event){if(soundPreset==5||System.currentTimeMillis()-lastCustomHit>160L)return;Object raw=field(event,"name");if(raw==null)raw=call(event,"getName");String name=String.valueOf(raw).toLowerCase();if(name.contains("hurt")||name.contains("hit"))suppressSound(event);}
    public static void onMatchFinished(boolean win,int duration,int kills,int finals,int beds){result=new Result(win,duration,kills,finals,beds);resultUntil=System.currentTimeMillis()+9000L;}
    public static boolean hasResult(){return result!=null&&System.currentTimeMillis()<=resultUntil;}
    public static void render(Object minecraft,int sw,int sh){mc=minecraft;if(result==null||System.currentTimeMillis()>resultUntil)return;float in=Math.min(1F,(resultUntil-System.currentTimeMillis()>8500L?(9000-(resultUntil-System.currentTimeMillis()))/300F:1F));int w=300,h=145,x=sw/2-w/2,y=sh/2-h/2;DrawUtil.shadow(x,y,x+w,y+h,9);DrawUtil.rounded(x,y,x+w,y+h,9,0xEF10131C);DrawUtil.gradient(x,y,x+w,y+4,accent(),accent2());DrawUtil.rounded(x+16,y+17,x+62,y+63,23,result.win?0xE025704C:0xE06A2638);center(result.win?"§a§lW":"§c§lL",x+39,y+35,0xFFFFFFFF);draw(result.win?"§a§lПОБЕДА":"§c§lПОРАЖЕНИЕ",x+76,y+20,0xFFFFFFFF);draw("§7Матч завершён  •  §f"+time(result.duration),x+76,y+38,0xFFFFFFFF);DrawUtil.rect(x+16,y+76,x+w-16,y+77,0x25FFFFFF);stat("Убийства",result.kills,x+20,y+91);stat("Финалы",result.finals,x+91,y+91);stat("Кровати",result.beds,x+162,y+91);stat("Очки",result.score,x+233,y+91);draw("§8Экран исчезнет автоматически",x+16,y+129,0xFF96919F);}
    public static int accent(){return new int[]{0xFFB060FF,0xFF45D7FF,0xFFFF78B5,0xFFFF4D68}[Math.max(0,Math.min(3,uiTheme))];}
    public static int accent2(){return new int[]{0xFF45D7FF,0xFF8E7CFF,0xFFFFD0E3,0xFFFFA34D}[Math.max(0,Math.min(3,uiTheme))];}
    public static int moduleCount(int cat){return new int[]{5,5,5,3,2,1,1}[Math.max(0,Math.min(6,cat))];}
    public static String moduleName(int c,int i){String[][]n={{"Мягкое доведение","Траектория стрелы","Частицы удара","Индикатор урона","Режим концентрации"},{"BedWars HUD","Помощник магазина","Автоперезаход","Враг у базы","Таймеры генераторов"},{"Свой scoreboard","Красивый чат","Киллфид","Пинг","CPS"},{"Эмодзи","Входящий перевод","Упоминания"},{"Скин Киры","Плащ QMods"},{"Лёгкий режим"},{"Звук удара: "+SOUND_NAMES[soundPreset]}};return n[c][i];}
    public static String moduleDesc(int c,int i){String[][]d={{"Плавная помощь при стрельбе","Физика полёта и столкновения","Лёгкий эффект при попадании","Показывает сторону атаки","Скрывает лишний HUD в бою"},{"Ресурсы и состояние матча","Стоимость и быстрые вкладки","Быстрый /leave → /rejoin","Локальная тревога о вторжении","Алмазы и изумруды"},{"Темы и чистые строки","Стили, время и прозрачность","Иконки и финальные убийства","Задержка соединения","Клики в секунду"},{"Текстовые комбинации","Автоперевод на русский","Выделение твоего ника"},{"Только на твоём клиенте","Локальный косметический плащ"},{"Оптимизация для Intel HD 4000"},{"ПКМ или ЛКМ — следующий пресет"}};return d[c][i];}
    public static boolean moduleEnabled(int c,int i){if(c==0)return new boolean[]{QModsTools.config.aimAssist,QModsTools.config.trajectory,QModsTools.config.hitParticles,QModsTools.config.damageIndicator,focusMode}[i];if(c==1)return new boolean[]{QModsTools.config.bedWarsHud,QModsTools.config.shopHelper,QModsTools.config.autoVoidRejoin,QModsTools.config.baseAlert,QModsTools.config.genTimers}[i];if(c==2)return new boolean[]{QModsTools.config.customScoreboard,QModsTools.config.customChat,QModsTools.config.killFeed,QModsTools.config.pingHud,QModsTools.config.cpsHud}[i];if(c==3)return new boolean[]{QModsTools.config.emojiReplace,QModsTools.config.translateIncoming,QModsTools.config.chatMentionHighlight}[i];if(c==4)return new boolean[]{QModsTools.config.localKiraSkin,QModsTools.config.localQModsCape}[i];if(c==5)return QModsTools.config.lowPower;return soundPreset!=5;}
    public static void toggle(int c,int i){if(c==0){if(i==0)QModsTools.config.aimAssist=!QModsTools.config.aimAssist;else if(i==1)QModsTools.config.trajectory=!QModsTools.config.trajectory;else if(i==2)QModsTools.config.hitParticles=!QModsTools.config.hitParticles;else if(i==3)QModsTools.config.damageIndicator=!QModsTools.config.damageIndicator;else focusMode=!focusMode;}else if(c==1){if(i==0)QModsTools.config.bedWarsHud=!QModsTools.config.bedWarsHud;else if(i==1)QModsTools.config.shopHelper=!QModsTools.config.shopHelper;else if(i==2)QModsTools.config.autoVoidRejoin=!QModsTools.config.autoVoidRejoin;else if(i==3)QModsTools.config.baseAlert=!QModsTools.config.baseAlert;else QModsTools.config.genTimers=!QModsTools.config.genTimers;}else if(c==2){if(i==0)QModsTools.config.customScoreboard=!QModsTools.config.customScoreboard;else if(i==1)QModsTools.config.customChat=!QModsTools.config.customChat;else if(i==2)QModsTools.config.killFeed=!QModsTools.config.killFeed;else if(i==3)QModsTools.config.pingHud=!QModsTools.config.pingHud;else QModsTools.config.cpsHud=!QModsTools.config.cpsHud;}else if(c==3){if(i==0)QModsTools.config.emojiReplace=!QModsTools.config.emojiReplace;else if(i==1)QModsTools.config.translateIncoming=!QModsTools.config.translateIncoming;else QModsTools.config.chatMentionHighlight=!QModsTools.config.chatMentionHighlight;}else if(c==4){if(i==0)QModsTools.config.localKiraSkin=!QModsTools.config.localKiraSkin;else QModsTools.config.localQModsCape=!QModsTools.config.localQModsCape;}else if(c==5)QModsTools.config.lowPower=!QModsTools.config.lowPower;else nextSound();QModsTools.config.save();save();}
    public static void nextTheme(){uiTheme=(uiTheme+1)%THEMES.length;save();}public static void nextSound(){soundPreset=(soundPreset+1)%SOUND_NAMES.length;previewSound();save();}
    public static void previewSound(){lastCustomHit=System.currentTimeMillis();playPreset();}
    public static void openLegacy(Object parent){try{Class<?> gs=Class.forName("net.minecraft.client.gui.GuiScreen"),old=Class.forName("ru.qmurzik.qmodstools.gui.GuiSettings");Object screen=old.getConstructor(gs).newInstance(parent);call(mc,new String[]{"func_147108_a","displayGuiScreen"},new Class[]{gs},screen);}catch(Throwable ignored){}}
    private static void playPreset(){if(soundPreset==5)return;String[]names={"random.orb","random.pop","random.click","dig.glass","random.levelup"};float[]pitch={1.15F,1.45F,1.65F,1.55F,1.9F};Object p=field(mc,"field_71439_g","thePlayer");call(p,new String[]{"func_85030_a","playSound"},new Class[]{String.class,float.class,float.class},names[soundPreset],0.72F,pitch[soundPreset]);}
    private static void load(){if(loaded)return;Object dir=field(mc,"field_71412_D","mcDataDir");if(!(dir instanceof File))return;settingsFile=new File(new File((File)dir,"config"),"qmods-ui.cfg");settingsFile.getParentFile().mkdirs();Properties p=new Properties();try{if(settingsFile.exists()){FileInputStream in=new FileInputStream(settingsFile);p.load(in);in.close();}focusMode=Boolean.parseBoolean(p.getProperty("focus",String.valueOf(focusMode)));focusSeconds=clamp(Integer.parseInt(p.getProperty("focus_seconds","3")),2,8);soundPreset=clamp(Integer.parseInt(p.getProperty("sound","0")),0,5);uiTheme=clamp(Integer.parseInt(p.getProperty("theme","0")),0,3);}catch(Exception ignored){}loaded=true;}
    public static void save(){if(settingsFile==null)return;try{Properties p=new Properties();p.setProperty("focus",String.valueOf(focusMode));p.setProperty("focus_seconds",String.valueOf(focusSeconds));p.setProperty("sound",String.valueOf(soundPreset));p.setProperty("theme",String.valueOf(uiTheme));FileOutputStream out=new FileOutputStream(settingsFile);p.store(out,"QMods 1.7 UI");out.close();}catch(Exception ignored){}}
    private static void stat(String n,int v,int x,int y){draw("§7"+n,x,y,0xFFAAA6B3);draw("§f§l"+v,x,y+14,0xFFFFFFFF);}private static String time(int s){return String.format("%02d:%02d",s/60,s%60);}private static int clamp(int n,int a,int b){return Math.max(a,Math.min(b,n));}
    private static void draw(String s,int x,int y,int c){Object f=field(mc,"field_71466_p","fontRendererObj");call(f,new String[]{"func_175065_a","drawString"},new Class[]{String.class,float.class,float.class,int.class,boolean.class},s,(float)x,(float)y,c,true);}private static void center(String s,int x,int y,int c){Object f=field(mc,"field_71466_p","fontRendererObj");Object w=call(f,new String[]{"func_78256_a","getStringWidth"},new Class[]{String.class},s);draw(s,x-(w instanceof Number?((Number)w).intValue()/2:s.length()*3),y,c);}
    private static Object field(Object o,String...n){if(o==null)return null;for(Class<?>c=o.getClass();c!=null;c=c.getSuperclass())for(String s:n)try{Field f=c.getDeclaredField(s);f.setAccessible(true);return f.get(o);}catch(Exception ignored){}return null;}private static boolean setField(Object o,Object v,String...n){if(o==null)return false;for(Class<?>c=o.getClass();c!=null;c=c.getSuperclass())for(String s:n)try{Field f=c.getDeclaredField(s);f.setAccessible(true);f.set(o,v);return true;}catch(Exception ignored){}return false;}
    private static void suppressSound(Object event){if(event==null)return;try{Method m=find(event.getClass(),"setResultSound",1);m.setAccessible(true);m.invoke(event,new Object[]{null});return;}catch(Exception ignored){}setField(event,null,"result");}
    private static Object call(Object o,String...n){return call(o,n,new Class<?>[0],new Object[0]);}private static Object call(Object o,String[]n,Object...a){return call(o,n,new Class<?>[0],a);}private static Object call(Object o,String[]n,Class<?>[]t,Object...a){if(o==null)return null;for(String s:n)try{Method m=find(o.getClass(),s,a.length);m.setAccessible(true);return m.invoke(o,a);}catch(Exception ignored){}return null;}private static Method find(Class<?>c,String n,int count)throws Exception{for(Class<?>x=c;x!=null;x=x.getSuperclass())for(Method m:x.getDeclaredMethods())if(m.getName().equals(n)&&m.getParameterTypes().length==count)return m;throw new NoSuchMethodException(n);}
    private static final class Result{final boolean win;final int duration,kills,finals,beds,score;Result(boolean w,int d,int k,int f,int b){win=w;duration=d;kills=k;finals=f;beds=b;score=k*20+f*45+b*100+(w?250:0);}}
}
